    fprintf( "***********ingrese 3 numeros*******************")
    n1 = input("primer numero\n")
    n2 = input("segundo numero\n")
    n3 = input("tercer numero\n")
    fid = fopen('tresnum.txt','a');
    fprintf(fid,"\nNumeros:%d %d %d ",n1,n2,n3)

if (n1 == n2) & (n1 != n3)
     fprintf("el distinto es %d",n3)
     fprintf(fid,"el distinto es %d",n3)
elseif (n1 == n3) & (n1 != n2)
     fprintf("el distinto es %d",n2)
     fprintf(fid,"el distinto es %d",n2)
elseif (n3 == n2) & (n1 != n3)
     fprintf("el distinto es %d", n1)
     fprintf(fid,"el distinto es %d",n1)
elseif (n1 > n2) & (n1 > n3)
     fprintf("la suma es %d", n1 + n2 + n3)
     fprintf(fid,"la suma es %d", n1 + n2 + n3)
elseif (n2 > n1) & (n2 > n3)
     fprintf("El producto es %d",n1*n2*n3)
     fprintf(fid,"El producto es %d",n1*n2*n3)
elseif (n3 > n2 & n3 > n1)
     fprintf("concatenado: %d%d%d ", n1,n2,n3)
     fprintf(fid,"concatenado: %d%d%d ", n1,n2,n3)
elseif (n1 == n2) & (n2 == n3)
     fprintf("todos son iguales")
     fprintf(fid,"todos son iguales")
else
     fprintf("no esta en las opciones")
end
    fclose(fid) 